### ISSUE TITLE
3-6.0.0-alpine3.7 actually runs Python 2.7.13 / Pypy 5.10

### ISSUE THREAD

**Issue by jacobsvante** [JayH5/alpine-pypy#27]
As seen here:

```
> docker run -it --rm jamiehewland/alpine-pypy-build:3-6.0.0-alpine3.7 pypy --version
Python 2.7.13 (0e7ea4fe15e82d5124e805e2e4a37cae1a402d4b, Feb 03 2018, 16:09:51)
[PyPy 5.10.0 with GCC 6.4.0]
```

**Comment by jacobsvante** [comment]
Perhaps Docker Hub's auto-build feature could help with ensuring correct versions being published.

It would also make users more secure in what the image they pull contains.

**Comment by JayH5** [comment]
You want the `jamiehewland/alpine-pypy:3-6.0.0-alpine3.7` image (no `-build`) which are built from the [`JayH5/docker-alpine-pypy`](https://github.com/JayH5/docker-alpine-pypy) repo. Sorry, I know it can be a bit confusing 😕.

The `-build` images from this repo are specifically for _building_ PyPy and so usually use an older version of PyPy to build the latest version.

**Comment by jacobsvante** [comment]
Thanks @JayH5. Sorry for the confusion on my part!

**Comment by jacobsvante** [comment]
@JayH5 Btw how do you feel about setting up auto-builds on Docker Hub? We'd love to feel secure in what we're actually pulling! I can open a separate issue for this if you'd like.

**Comment by JayH5** [comment]
@jmagnusson this is difficult for a number of reasons 😞.

So this repo is for 2 things:
 1. Docker images with the PyPy source and some build tools. These are used for building PyPy, like I said.
 2. Tarballs are built like those available on the [PyPy downloads page](http://pypy.org/download.html) and uploaded to [this repo's releases](https://github.com/JayH5/alpine-pypy) using the Docker images.

The `docker-alpine-pypy` repo has Dockerfiles that then download and install the release tarballs.

All Docker images in both repos are automatically built and uploaded to Docker Hub using Travis CI. It could be possible to use Docker automated builds for that if there is a benefit of some kind, but in my experience Travis is much more flexible in terms of things like tagging images.

The difficult part is building the tarball. When I last built PyPy3 6.0.0 on an 8GB DigitalOcean machine it took nearly 4 hours:
```
real    231m17.946s
user    0m12.630s
sys     0m25.609s
```
...you need at least ~6GB RAM to build PyPy as well or the build will crash. This is clearly not something that one can do within the limits of a standard CI system like Travis or Docker automated builds. So building the tarball is currently a manual process that I do (when I have time).

So we can automate building the Docker images but without automating building/signing the tarball I don't think there's much advantage since that is the important chunk of code you're running.

**Comment by jacobsvante** [comment]
@JayH5 I understand. Thanks for the thorough explanation, much appreciated ❤
